In [3]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 텐서 : 스칼라 25 - 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태  [1,2,3,4]
# 2차원 텐서(행렬) : 행 과 열로 이루어진 데이터 표데이터, 흑백 이미지(가로픽셀 x 세로픽셀)
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R G B)
# 고차원 텐서 : 동영상 : 이미지개수 x 가로픽셀 x 세로픽셀 x 채널정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병열연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [4]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [5]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[9.4778e-38, 1.6872e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.7847, 0.3611, 0.2958, 0.2748],
        [0.6875, 0.0123, 0.3892, 0.8445],
        [0.3218, 0.7378, 0.3130, 0.3140]])

In [7]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [8]:
# 1로 채워진 텐서
x = torch.ones(3,4, dtype=torch.long)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [9]:
import numpy as np
print( torch.tensor( [3.5,3,2.1] ) )
print( np.array( [3.5,3,2.1] )  )

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [10]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype= torch.float)
x,  y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[-0.3833, -0.5095, -1.4962,  1.1209],
         [-1.3020,  1.1520,  1.0878,  0.8906],
         [-1.6377, -2.3603, -0.5904,  1.5153]]))

In [11]:
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x ,  y, x+y

(tensor([[0.2996, 0.3323, 0.1200, 0.9609],
         [0.9046, 0.5417, 0.0606, 0.5756],
         [0.7339, 0.9361, 0.0176, 0.1009]]),
 tensor([[0.4932, 0.6987, 0.1948, 0.0320],
         [0.8751, 0.8992, 0.2938, 0.6570],
         [0.1957, 0.4422, 0.9751, 0.3539]]),
 tensor([[0.7928, 1.0310, 0.3147, 0.9928],
         [1.7798, 1.4409, 0.3544, 1.2327],
         [0.9297, 1.3782, 0.9927, 0.4548]]))

In [12]:
torch.add(x,y)

tensor([[0.7928, 1.0310, 0.3147, 0.9928],
        [1.7798, 1.4409, 0.3544, 1.2327],
        [0.9297, 1.3782, 0.9927, 0.4548]])

In [13]:
#in-place   y = y + x   y += x
y.add_(x)

tensor([[0.7928, 1.0310, 0.3147, 0.9928],
        [1.7798, 1.4409, 0.3544, 1.2327],
        [0.9297, 1.3782, 0.9927, 0.4548]])

In [14]:
y

tensor([[0.7928, 1.0310, 0.3147, 0.9928],
        [1.7798, 1.4409, 0.3544, 1.2327],
        [0.9297, 1.3782, 0.9927, 0.4548]])

In [15]:
# 행렬 곱셈 
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y),x@y # 파이썬 3.5  x@y

(tensor([[0.5070, 0.9678, 0.8382, 0.4854],
         [0.4530, 0.5921, 0.3456, 0.5103],
         [0.2659, 0.9277, 0.6233, 0.7622]]),
 tensor([[0.7058, 0.4409, 0.4608, 0.4610, 0.1140],
         [0.1012, 0.5858, 0.4166, 0.5353, 0.5222],
         [0.2655, 0.8674, 0.3198, 0.6214, 0.3344],
         [0.6949, 0.0902, 0.1652, 0.3895, 0.9216]]),
 tensor([[1.0156, 1.5614, 0.9850, 1.4618, 1.2909],
         [0.8261, 0.8925, 0.6502, 0.9394, 0.9468],
         [0.9766, 1.2701, 0.8342, 1.3033, 1.4256]]),
 tensor([[1.0156, 1.5614, 0.9850, 1.4618, 1.2909],
         [0.8261, 0.8925, 0.6502, 0.9394, 0.9468],
         [0.9766, 1.2701, 0.8342, 1.3033, 1.4256]]))

In [16]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item() )

(tensor(0.9188), 0.9187768697738647, torch.Tensor, float)